lavaseco_homepage:
    path:     /
    defaults: { _controller: LavasecoBundle:Home:index }

lavaseco_terms:
    path:     /condiciones
    defaults: { _controller: LavasecoBundle:Home:terms }

lavaseco_sales:
    path:     /venta
    defaults: { _controller: LavasecoBundle:Sale:index }

lavaseco_cash:
    path:     /venta/caja/{egress}
    defaults: { _controller: LavasecoBundle:CashTransaction:index, egress: 0 }
    requirements:
        egress:  \d+

lavaseco_orders:
    path:     /orden/{processId}
    defaults: { _controller: LavasecoBundle:Orders:index, processId: 0 }
    requirements:
        processId:  \d+

lavaseco_Bills:
    path:     /facturas
    defaults: { _controller: LavasecoBundle:Bill:index }
            
lavaseco_setting_bill_content:
    path:     /configuracion/factura
    defaults: { _controller: LavasecoBundle:Bill:setting }

lavaseco_setting_descriptions:
    path:     /configuracion/descriptores
    defaults: { _controller: LavasecoBundle:Description:setting }

lavaseco_setting_service_categories:
    path:     /configuracion/servicios
    defaults: { _controller: LavasecoBundle:Service:setting }

lavaseco_setting_customers:
    path:     /configuracion/clientes
    defaults: { _controller: LavasecoBundle:Customer:create }

lavaseco_setting_sale_point:
    path:     /configuracion/puntoventa/{salePointId}
    defaults: { _controller: LavasecoBundle:SalePoint:index, salePointId: 0 }   
    requirements:
        salePointId:  \d+

lavaseco_setting_branch_office:
    path:     /configuracion/sucursal/{branchOfficeId}
    defaults: { _controller: LavasecoBundle:BranchOffice:index, branchOfficeId: 0 }
    requirements:
        branchOfficeId:  \d+
        
lavaseco_setting_loyalty:
    path:     /configuracion/fidelidad
    defaults: { _controller: LavasecoBundle:Loyalty:index }

lavaseco_setting_corporation:
    path:     /configuracion/webpage
    defaults: { _controller: LavasecoBundle:Corporation:index }

lavaseco_report_dashboard:
    path:     /reportes/dashboard
    defaults: { _controller: LavasecoBundle:Report:dashboard }

lavaseco_report_daily_sale:
    path:     /reportes/venta/diaria
    defaults: { _controller: LavasecoBundle:Report:dailySale }

lavaseco_report_service_sale:
    path:     /reportes/venta/servicios
    defaults: { _controller: LavasecoBundle:Report:serviceSale }

lavaseco_report_user_sale:
    path:     /reportes/venta/usuarios
    defaults: { _controller: LavasecoBundle:Report:userSale }

lavaseco_report_sale_point:
    path:     /reportes/venta/puntoventa
    defaults: { _controller: LavasecoBundle:Report:salepoint }

lavaseco_report_cash_transaction:
    path:     /reportes/movimientos/puntoventa
    defaults: { _controller: LavasecoBundle:Report:cashTransaction }

lavaseco_report_inventory:
    path:     /reportes/inventario
    defaults: { _controller: LavasecoBundle:Report:inventory }   

lavaseco_report_inventory_excel:
    path:     /reportes/excel/inventario
    defaults: { _controller: LavasecoBundle:Report:inventoryExcel }   
    
#app Service-------------------------------------------------------------------        
lavaseco_client_home:
    path:     /app
    defaults: { _controller: LavasecoBundle:Client:index }

lavaseco_client_login:
    path:     /app/login
    defaults: { _controller: LavasecoBundle:Client:login }
    
lavaseco_client_orders:
    path:     /app/orders
    defaults: { _controller: LavasecoBundle:Client:orders }

lavaseco_client_invoices:
    path:     /app/invoices
    defaults: { _controller: LavasecoBundle:Client:invoice }

#Ajax Service-------------------------------------------------------------------        
lavaseco_api_service_category:
    path:     /api/service/category/{serviceCategoryId}
    defaults: { _controller: LavasecoBundle:Service:getServiceCategoryId, serviceCategoryId: 0}
    methods:  [GET]
    requirements:
        serviceCategoryId:  \d+

lavaseco_api_sale_service_category:
    path:     /api/venta/service/category/{serviceCategoryId}
    defaults: { _controller: LavasecoBundle:Service:getServiceByServiceCategoryId, serviceCategoryId: 0}
    methods:  [GET]
    requirements:
        serviceCategoryId:  \d+

lavaseco_api_add_service_category:
    path:     /api/service/category
    defaults: { _controller: LavasecoBundle:Service:addServiceCategory }
    methods:  [POST]

lavaseco_api_service_descriptions:
    path:     /api/service/descriptions/{serviceCategoryId}
    defaults: { _controller: LavasecoBundle:Service:getServiceAndDescriptionsByServiceCategoryId, serviceCategoryId: 0}
    methods:  [GET]
    requirements:
        serviceCategoryId:  \d+

lavaseco_api_descriptors:
    path:     /api/descriptors
    defaults: { _controller: LavasecoBundle:Service:getDescriptors }
    methods:  [GET]

#permitido solo para los usuarios que tienen acceso a venta
lavaseco_api_search_customer:
    path:     /api/search/customer
    defaults: { _controller: LavasecoBundle:Customer:search }
    methods:  [POST]
    
#permitido solo para los usuarios que tienen acceso a venta    
lavaseco_api_get_customer:
    path:     /api/customer/{customerId}
    defaults: { _controller: LavasecoBundle:Customer:getCustomer, customerId:0}
    methods:  [GET]
    requirements:
        customerId:  \d+

lavaseco_api_validate_customer:
    path:     /api/customer/{email}
    defaults: { _controller: LavasecoBundle:Customer:validateEmail, email: ''}
    methods:  [GET]
        
lavaseco_api_create_customer:
    path:     /api/customer
    defaults: { _controller: LavasecoBundle:Customer:register }
    methods:  [POST]

lavaseco_api_sale_billing:
    path:     /api/sale/billing
    defaults: { _controller: LavasecoBundle:Bill:saveBilling }
    methods:  [POST]

lavaseco_api_orders_tikets:
    path:     /api/order/tiket/{billId}
    defaults: { _controller: LavasecoBundle:Bill:getTiketByBillId, billId: 0 }
    methods:  [GET]
    requirements:
        billId:  \d+

lavaseco_api_order_change_processState:
    path:     /api/order/next/processState
    defaults: { _controller: LavasecoBundle:Orders:changeProcessState }
    methods:  [POST] 

lavaseco_api_bill:
    path:     /api/bill/{billId}
    defaults: { _controller: LavasecoBundle:Bill:getBillById, billId: 0 }
    methods:  [GET]
    requirements:
        billId:  \d+
        
lavaseco_api_bill_deliver:
    path:     /api/bill/delivery
    defaults: { _controller: LavasecoBundle:Bill:deliver }
    methods:  [POST]
        
lavaseco_api_bill_refund:
    path:     /api/bill/refund
    defaults: { _controller: LavasecoBundle:Bill:refund }
    methods:  [POST] 
        
lavaseco_api_bill_history:
    path:     /api/bill/history/{billId}
    defaults: { _controller: LavasecoBundle:Bill:getHistoryByBillId, billId: 0 }
    methods:  [GET]
    requirements:
        billId:  \d+
        
lavaseco_api_sale_point:
    path:     /api/sale/point
    defaults: { _controller: LavasecoBundle:SalePoint:register }
    methods:  [POST]

lavaseco_api_sale_point_active:
    path:     /api/sale/point/active
    defaults: { _controller: LavasecoBundle:SalePoint:getSalePoint }
    methods:  [POST]
    
lavaseco_api_pay_method:
    path:     /api/pay/method
    defaults: { _controller: LavasecoBundle:Bill:getPayMethod }
    methods:  [GET]
    
lavaseco_api_print:
    path:     /api/print/{officeBranchId}
    defaults: { _controller: LavasecoBundle:Print:unprinted }
    methods:  [POST]

lavaseco_api_print_bill:
    path:     /api/print/bill/
    defaults: { _controller: LavasecoBundle:Print:pirntBill }
    methods:  [POST]


lavaseco_api_report_daily_sale:
    path:     /api/report/daily/sale
    defaults: { _controller: LavasecoBundle:Report:getDailySale }
    methods:  [POST]    

lavaseco_api_report_sale_point:
    path:     /api/report/salepoint
    defaults: { _controller: LavasecoBundle:Report:getSalePoint }
    methods:  [POST]

lavaseco_api_report_cash_transaction:
    path:     /api/report/transaction
    defaults: { _controller: LavasecoBundle:Report:getCashTransaction }
    methods:  [POST]
    
lavaseco_api_bill_paymet:
    path:     /api/bill/payment
    defaults: { _controller: LavasecoBundle:Bill:payment }
    methods:  [POST]