lavaseco_homepage:
    path:     /
    defaults: { _controller: LavasecoBundle:Home:index }

lavaseco_sales:
    path:     /venta
    defaults: { _controller: LavasecoBundle:Sale:index }

lavaseco_settign_bill_content:
    path:     /configuracion/factura
    defaults: { _controller: LavasecoBundle:Bill:setting }

lavaseco_settign_service_categories:
    path:     /configuracion/servicios
    defaults: { _controller: LavasecoBundle:Service:setting }

#Ajax Service-------------------------------------------------------------------
lavaseco_api_service:
    path:     /api/service/{subServiceCategoryId}
    defaults: { _controller: LavasecoBundle:Sale:getServiceBySubserviceCategory }
    methods:  [GET]
