lavaseco_homepage:
    path:     /
    defaults: { _controller: LavasecoBundle:Home:index }

lavaseco_sales:
    path:     /venta
    defaults: { _controller: LavasecoBundle:Sale:index }

lavaseco_settign_bill_content:
    path:     /configuracion/factura
    defaults: { _controller: LavasecoBundle:Bill:setting }

lavaseco_settign_descriptions:
    path:     /configuracion/descriptores
    defaults: { _controller: LavasecoBundle:Description:setting }

lavaseco_settign_service_categories:
    path:     /configuracion/servicios
    defaults: { _controller: LavasecoBundle:Service:setting }

#Ajax Service-------------------------------------------------------------------
lavaseco_api_service_category:
    path:     /api/service/category/{serviceCategoryId}
    defaults: { _controller: LavasecoBundle:Service:getServiceByServiceCategoryId, serviceCategoryId: 0}
    methods:  [GET]
    requirements:
        serviceCategoryId:  \d+

lavaseco_api_add_service_category:
    path:     /api/service/category
    defaults: { _controller: LavasecoBundle:Service:addServiceCategory }
    methods:  [POST]

lavaseco_api_service_descriptions:
    path:     /api/service/descriptions/{serviceCategoryId}
    defaults: { _controller: LavasecoBundle:Service:getServiceAndDescriptionsByServiceCategoryId, serviceCategoryId: 0}
    methods:  [GET]
    requirements:
        serviceCategoryId:  \d+

lavaseco_api_descriptors:
    path:     /api/descriptors
    defaults: { _controller: LavasecoBundle:Service:getDescriptors }
    methods:  [GET]
