lavaseco_homepage:
    path:     /
    defaults: { _controller: LavasecoBundle:Home:index }

lavaseco_sales:
    path:     /venta
    defaults: { _controller: LavasecoBundle:Sale:index }

lavaseco_settign_bill_content:
    path:     /configuracion/factura
    defaults: { _controller: LavasecoBundle:Bill:setting }

lavaseco_settign_descriptions:
    path:     /configuracion/descriptores
    defaults: { _controller: LavasecoBundle:Description:setting }

lavaseco_settign_service_categories:
    path:     /configuracion/servicios
    defaults: { _controller: LavasecoBundle:Service:setting }

lavaseco_settign_users:
    path:     /configuracion/usuarios
    defaults: { _controller: LavasecoBundle:User:create }

#Ajax Service-------------------------------------------------------------------
lavaseco_api_service_category:
    path:     /api/service/category/{serviceCategoryId}
    defaults: { _controller: LavasecoBundle:Service:getServiceByServiceCategoryId, serviceCategoryId: 0}
    methods:  [GET]
    requirements:
        serviceCategoryId:  \d+

lavaseco_api_add_service_category:
    path:     /api/service/category
    defaults: { _controller: LavasecoBundle:Service:addServiceCategory }
    methods:  [POST]

lavaseco_api_service_descriptions:
    path:     /api/service/descriptions/{serviceCategoryId}
    defaults: { _controller: LavasecoBundle:Service:getServiceAndDescriptionsByServiceCategoryId, serviceCategoryId: 0}
    methods:  [GET]
    requirements:
        serviceCategoryId:  \d+

lavaseco_api_descriptors:
    path:     /api/descriptors
    defaults: { _controller: LavasecoBundle:Service:getDescriptors }
    methods:  [GET]

#permitido solo para los usuarios que tienen acceso a venta
lavaseco_api_search_user:
    path:     /api/tool/user
    defaults: { _controller: LavasecoBundle:User:search }
    methods:  [POST]
    
#permitido solo para los usuarios que tienen acceso a venta    
lavaseco_api_get_user:
    path:     /api/user/{userId}
    defaults: { _controller: LavasecoBundle:User:getByUserId, userId:0}
    methods:  [GET]
    requirements:
        userId:  \d+

lavaseco_api_validate_user:
    path:     /api/user/{email}
    defaults: { _controller: LavasecoBundle:User:validateEmail, email:''}
    methods:  [GET]
        
lavaseco_api_create_user:
    path:     /api/user
    defaults: { _controller: LavasecoBundle:User:register }
    methods:  [POST]

lavaseco_api_sale_billing:
    path:     /api/sale/billing
    defaults: { _controller: LavasecoBundle:Bill:saveBilling }
    methods:  [POST]