services:            
    lavaseco.app_configuration:
        class: LavasecoBundle\Services\AppConfiguration
        arguments: []
        
    lavaseco.form.registration:
        class: LavasecoBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: Lavaseco_user_registration }