services:
    app.form.registration:
        class: LavasecoBundle\Form\UserType
        tags:
            - { name: form.type, alias: lavaseco_user_registration }
                
    lavaseco.app_configuration:
        class: LavasecoBundle\Services\AppConfiguration
        arguments: []    