<?php

namespace LavasecoBundle\Repository;

/**
 * AbstractServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbstractServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
