<?php

namespace LavasecoBundle\Repository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends \Doctrine\ORM\EntityRepository {
    public function findAnonimusAddress($nickname){
        $this->findOneBy(
                array(
                    'nickname' => $nickname, 
                    'Customer' => null,
                    'BranchOffice' => null,
                )
            );
    } 
}
