<?php

namespace LavasecoBundle\Repository;

/**
 * BillContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillContentRepository extends \Doctrine\ORM\EntityRepository
{
}
