<?php

namespace LavasecoBundle\Repository;

/**
 * BillStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillStateRepository extends \Doctrine\ORM\EntityRepository
{
}
