<?php

namespace LavasecoBundle\Repository;

/**
 * BillHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
