<?php

namespace LavasecoBundle\Repository;

/**
 * BranchOfficeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BranchOfficeRepository extends \Doctrine\ORM\EntityRepository
{
}
