<?php

namespace LavasecoBundle\Repository;

/**
 * CashTransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CashTransactionRepository extends \Doctrine\ORM\EntityRepository
{
}
