<?php

namespace LavasecoBundle\Repository;

/**
 * CategoryStateObjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryStateObjectRepository extends \Doctrine\ORM\EntityRepository
{
}
