<?php

namespace LavasecoBundle\Repository;

/**
 * ObjectStateReceivedServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectStateReceivedServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
