<?php

namespace LavasecoBundle\Repository;

/**
 * PayDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
