<?php

namespace LavasecoBundle\Repository;

/**
 * PayMethodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayMethodRepository extends \Doctrine\ORM\EntityRepository
{
}
