<?php

namespace LavasecoBundle\Repository;

/**
 * PaymentAgreementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentAgreementRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAvailables(){
        $query = $this->createQueryBuilder('pa')
                ->where('pa.disable = false')
                ->getQuery();

        return $query->getResult();
    }
}
