<?php

namespace LavasecoBundle\Repository;

/**
 * PaymentAgreementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentAgreementRepository extends \Doctrine\ORM\EntityRepository
{
}
