<?php

namespace LavasecoBundle\Repository;

/**
 * ProcessStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcessStateRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProces(){
        $qb = $this->createQueryBuilder('p');
        
        $query = $qb->where($qb->expr()->notIn('p.id', '7'))
                ->orderBy("p.id", 'ASC')
                ->getQuery();
        
        return $query->getResult();
        
    }
}