<?php

namespace LavasecoBundle\Repository;

/**
 * SalePointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalePointRepository extends \Doctrine\ORM\EntityRepository
{
}
