<?php

namespace LavasecoBundle\Repository;

/**
 * ServiceCategoryStatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceCategoryStateRepository extends \Doctrine\ORM\EntityRepository
{
}
