<?php

namespace LavasecoBundle\Repository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getServiceByServiceCategoryId($serviceCategoryId) {
        $query = $this->createQueryBuilder('s')
                ->where('s.serviceCategory = :serviceCategoryId')
                ->setParameter('serviceCategoryId', $serviceCategoryId)
                ->getQuery();

        return $query->getResult()[0];
    }
}
