<?php

namespace LavasecoBundle\Repository;

/**
 * ServiceCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceCategoryRepository extends \Doctrine\ORM\EntityRepository {
//subServiceCategories
    public function getFirstLevel() {
        $query = $this->createQueryBuilder('sc')
                ->where('sc.serviceCategory IS NULL')
                ->getQuery();
                
        return $query->getResult();
    }

}
