<?php

namespace LavasecoBundle\Repository;

/**
 * ServiceAttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceAttributeRepository extends \Doctrine\ORM\EntityRepository
{
}
