<?php

namespace LavasecoBundle\Repository;

/**
 * StateObjectRecevidServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StateObjectRecevidServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
