<?php

namespace LavasecoBundle\Repository;

/**
 * StateObjectDescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StateObjectDescriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
