<?php

namespace LavasecoBundle\Repository;

/**
 * TypeTransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeTransactionRepository extends \Doctrine\ORM\EntityRepository
{
}
