security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:   
        ROLE_CASHIER:     [ROLE_USER]
        ROLE_OPERATOR:    [ROLE_USER]
        ROLE_ADMIN:       [ROLE_OPERATOR, ROLE_CASHIER]  
        ROLE_MANAGER:     [ROLE_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_MANAGER] 

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_SUPER_ADMIN }
        
        - { path: ^/configuracion/factura, role: ROLE_MANAGER }
        - { path: ^/configuracion/fidelidad, role: ROLE_MANAGER }
        - { path: ^/configuracion/puntoventa, role: ROLE_MANAGER }
        - { path: ^/configuracion/webpage, role: ROLE_MANAGER }
        
        - { path: ^/venta/caja/, role: ROLE_ADMIN }
        - { path: ^/configuracion/servicios, role: ROLE_ADMIN }
        - { path: ^/configuracion/descriptores, role: ROLE_ADMIN }
        - { path: ^/api/descriptors, role: ROLE_ADMIN }
        - { path: ^/api/service/category, role: ROLE_ADMIN }
        
        - { path: ^/venta, role: ROLE_CASHIER }
        - { path: ^/facturas, role: ROLE_CASHIER  }
        - { path: ^/venta/caja, role: ROLE_CASHIER }
        - { path: ^/api/bill/, role: ROLE_CASHIER }
        - { path: ^/api/customer/, role: ROLE_CASHIER }
        - { path: ^/api/pay/method, role: ROLE_CASHIER }
        - { path: ^/api/bill/refund, role: ROLE_CASHIER }
        - { path: ^/api/bill/delivery, role: ROLE_CASHIER }
        - { path: ^/api/bill/history/, role: ROLE_CASHIER }
        - { path: ^/api/search/customer, role: ROLE_CASHIER }
        - { path: ^/api/service/descriptions/, role: ROLE_CASHIER }
        - { path: ^/api/venta/service/category/, role: ROLE_CASHIER }
        
        - { path: ^/orden, role: ROLE_OPERATOR }
        - { path: ^/orden/, role: ROLE_OPERATOR }
        - { path: ^/api/order/tiket/, role: ROLE_OPERATOR }
        - { path: ^/api/order/next/processState, role: ROLE_OPERATOR }